### ISSUE TITLE
Allow formatting files with multiple documents

### ISSUE THREAD

**Issue by rbtcollins** [mmlb/yamlfmt#16]
It is common (if unfortunate) in the k8s world to have a single file with multiple API documents:

```
foo:
...
---
bar:
...
---
quux:
```

Currently yamlfmt errors on this:
```
Traceback (most recent call last):
  File "/home/robertc/.pyenv/versions/3.8.2/bin/yamlfmt", line 55, in <module>
    sys.exit(main())
  File "/home/robertc/.pyenv/versions/3.8.2/bin/yamlfmt", line 48, in main
    round_trip(sout, sin)
  File "/home/robertc/.pyenv/versions/3.8.2/bin/yamlfmt", line 17, in round_trip
    y = yaml.round_trip_load(sin)
  File "/home/robertc/.pyenv/versions/3.8.2/lib/python3.8/site-packages/ruamel/yaml/main.py", line 1000, in round_trip_load
    return load(stream, RoundTripLoader, version, preserve_quotes=preserve_quotes)
  File "/home/robertc/.pyenv/versions/3.8.2/lib/python3.8/site-packages/ruamel/yaml/main.py", line 935, in load
    return loader._constructor.get_single_data()
  File "/home/robertc/.pyenv/versions/3.8.2/lib/python3.8/site-packages/ruamel/yaml/constructor.py", line 109, in get_single_data
    node = self.composer.get_single_node()
  File "/home/robertc/.pyenv/versions/3.8.2/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 83, in get_single_node
    raise ComposerError(
ruamel.yaml.composer.ComposerError: expected a single document in the stream
  in "FILE.yaml", line 3, column 1
but found another document
  in "FILEyaml", line 35, column 1
```

**Comment by mmlb** [comment]
yamlfmt has long been unmaintained, checkout https://github.com/lyz-code/yamlfix or https://github.com/prettier/prettier for alternatives.
