### ISSUE TITLE
Failed to install on osx

### ISSUE THREAD

**Issue by rjcoelho** [mmlb/yamlfmt#6]
$ python3 -m pip install yamlfmt 
Collecting yamlfmt
  Using cached https://files.pythonhosted.org/packages/df/82/003e1cdc5dcb181d6290b2c80249e0ea7b86f8d95a55e730951158e219ef/yamlfm
t-0.1.6-py2.py3-none-any.whl
Collecting ruamel.yaml<0.15 (from yamlfmt)
  Using cached https://files.pythonhosted.org/packages/cf/86/7ef6c24317e20e6cef0eab407520d49f3d3836e454d5377bdcbcf03d385c/ruamel
.yaml-0.14.12.tar.gz
    Complete output from command python setup.py egg_info:
    /var/folders/_6/bnqb1vbj4xx_m_lx4wttn32w0000gp/T/tmp_ruamel_zs8ummw9/test_ruamel_yaml.c:6:8: warning: explicitly assigning v
alue of variable of type 'yaml_parser_t' (aka 'struct yaml_parser_s') to itself [-Wself-assign]
    parser = parser;  /* prevent warning */
    ~~~~~~ ^ ~~~~~~
    /var/folders/_6/bnqb1vbj4xx_m_lx4wttn32w0000gp/T/tmp_ruamel_zs8ummw9/test_ruamel_yaml.c:6:10: warning: variable 'parser' is
uninitialized when used here [-Wuninitialized]
    parser = parser;  /* prevent warning */
             ^~~~~~
    /var/folders/_6/bnqb1vbj4xx_m_lx4wttn32w0000gp/T/tmp_ruamel_zs8ummw9/test_ruamel_yaml.c:5:1: note: variable 'parser' is decl
ared here
    yaml_parser_t parser;
    ^
    2 warnings generated.
    Warning: 'keywords' should be a list, got type 'NoneType'
    sys.argv ['-c', 'egg_info', '--egg-base', 'pip-egg-info']
    test compiling test_ruamel_yaml
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_6/bnqb1vbj4xx_m_lx4wttn32w0000gp/T/pip-install-lsgyn50y/ruamel.yaml/setup.py", line 858, in <module>
        main()
      File "/private/var/folders/_6/bnqb1vbj4xx_m_lx4wttn32w0000gp/T/pip-install-lsgyn50y/ruamel.yaml/setup.py", line 847, in main
        setup(**kw)
      File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 108,in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 370, in __init__
        k: v for k, v in attrs.items()
      File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 267,in __init__
        getattr(self.metadata, "set_" + key)(val)
      File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 1203, in set_keywords
        self.keywords = _ensure_list(value, 'keywords')
      File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 40, in _ensure_list
        value = list(value)
    TypeError: 'NoneType' object is not iterable

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_6/bnqb1vbj4xx_m_lx4wttn32w0000gp/T/pip-install-lsgyn50y/ruamel.yaml/

**Comment by rjcoelho** [comment]
You should updated to latest ruamel.yaml

**Comment by mmlb** [comment]
Don't have a mac to test against, haven't seen this error on linux machines. PR welcome for a fix or bump to ruel.yaml >0.14.
